### ISSUE TITLE
Navigation drawer for 'Deployments' is empty

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform-mobile#1]
I added a deployment. But when I reveal it, nothing appears there:

![build](https://cloud.githubusercontent.com/assets/1136279/21196816/b7c852e8-c1fe-11e6-8e3b-6808b061ed43.png)

I'd expect to see the deployment, along the ability to "Manage deployments."

![mockup](https://cloud.githubusercontent.com/assets/1136279/21196862/eb167670-c1fe-11e6-9c58-f27ab008e554.png)

Note that the title in the drawer -- "Deployments" -- is truncated, which is not desirable.

**Comment by dalezak** [comment]
Some improvements
![sidemenu](https://cloud.githubusercontent.com/assets/91811/21208043/526baf48-c231-11e6-828c-4ff2552deeec.png)

**Comment by dalezak** [comment]
Alright, upon opening the side menu, the deployments list is refreshed, should be fixed now... closing issue.
