### ISSUE TITLE
User unable to post from iOS app on uploading image to a post.

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform-mobile#100]
Feedback from user on Intercom

"I have the following problem with my account: i cannot post from my mobile after i have selected the picture.
It says: post failed. There was a problem posting your response."

**Comment by aoduor** [comment]
I'm not sure if I should open up another issue for this, but we've got android users having trouble with image uploads as well.

A user on intercom narrowed this down to users on Android version 4.1.x and lower.

"They get message like "not enough memory" (but mobile gas a lot of free memory) or even worst once upload The image The page reload"

**Comment by aoduor** [comment]
More info from the user

"With two different LG devices with 2 versions of android I've the same problem: the page reload when I had an Image and in addiction I received the message: "Impossibile to complete the operation. Memory insufficient"

**Comment by aoduor** [comment]
So, user just clarified that this isn't on the native application, but on a mobile browser. I'll move this to platform issues.

**Comment by dalezak** [comment]
Oh, interesting, thanks for the update 👍
