### ISSUE TITLE
Allow users to add self hosted deployments onto mobile apps

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform-mobile#103]
Currently, addition of deployments is based solely on searching from .io records,

As a user, i'd like to be able to:-
1. Add a deployment URL if I know it off head already
2. Add a self hosted deployment URL to use with the mobile app.

**Comment by dalezak** [comment]
Related to https://github.com/ushahidi/platform-mobile/issues/55, waiting on web issue https://github.com/ushahidi/platform/issues/1638.

**Comment by brandonrosage** [comment]
## Proposed design solution

Upon arriving at the "Add deployment" screen, they're greeted with a search input with the placeholder text "Find deployment by name or URL."

![d3 add deployment](https://cloud.githubusercontent.com/assets/1136279/25343603/2cf6c968-28d5-11e7-858d-44a496447aa1.png)

While typing, Ushahidi uses some conventions for determining what type of data they're entering:

* Until they type either a `.` or a space, we don't assume anything about the data. We return .io deployments whose name _or_ URL matches.
* If they enter a space, we assume they're entering a deployment name and return .io deployments with matching names.
* If they enter a `.` or `http`, we assume they're entering a deployment URL and _both_ return .io deployments with matching URLs _and_ append a list item button to "Add deployment by its URL."

![d3 add deployment url](https://cloud.githubusercontent.com/assets/1136279/25345338/73796c4c-28da-11e7-88b9-dd347a72a5cb.png)

Naturally, if they paste in the URL for their custom deployment, no .io results will be returned and only the list item button will appear, making it easy to submit their URL.

By selecting "Add deployment by its URL," it's added to their list of deployments and their taken to that deployment's overview screen -- just as if they had selected a .io deployment.

cc/ @dalezak, @jshorland

**Comment by dalezak** [comment]
Great idea @brandonrosage!

**Comment by dalezak** [comment]
Hey @brandonrosage, looks like the deployment search currently only searches by name, for example https://api.ushahidi.io/deployments?q=dale.ushahidi.io.

Will users be confused when entering a ushahidi.io domain and not seeing anything in the search results?

**Comment by brandonrosage** [comment]
Ideally, we could adapt the API so that that search returned matching results for name & URL. In the interim, though, I think it'd reasonable to assume that a user that's typing their URL will see their deployment returned before the string gets too specific.

For example, "dale" returns your deployment. 
"dale.ushah" returns "Add deployment by its URL; dale.ushah"
"dale.ushahidi.io" returns "Add deployment by its URL; dale.ushahidi.io"

That's reasonable enough for now, if the API can't return both.

**Comment by dalezak** [comment]
Cool, we can do that :+1:

**Comment by dalezak** [comment]
Good news, this functionality has now been implemented, thanks to @willdoran's changes on the backend for https://github.com/ushahidi/platform/issues/1638!
