### ISSUE TITLE
Draft posts appearing when NOT logged in on iOS on timeline

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform-mobile#115]
I wasn't logged in and the draft post was appearing, but when I DID login, i don't see it on the response timeline. But I do see it on the web version when logged in. The post was submitted before adding additional fields to the survey on web, and I noted this behavior AFTER I added those fields to my survey on the web.

**Comment by dalezak** [comment]
@jshorland I believe this issue has been fixed with #114 and #116. 

The only time that draft posts should show in the timeline, is when they are created by that user since they are stored locally in the database.
