### ISSUE TITLE
Filtering by status doesn't appear to include archived

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform-mobile#116]
Doesn't show archived when I explicitly turn on that filter when logged in as admin, or logged out (iOS)

**Comment by dalezak** [comment]
Good catch on this one @jshorland!

Looks like for http://github.ushahidi.org/platform/docs/api/index.html#posts, the `status` parameter is optional and probably defaults to `published`, so thats why only those were showing in the response list. 

I'll need to alter how that request is being made, when logged out, pass `status=published` but when logged in pass `status=published,archived,draft`.

**Comment by dalezak** [comment]
I've reworked the way filtering works. 

Previously, it was only filtering existing reports based on the conditions. 

Now it's passing those conditions to the API so should be a lot more powerful.
