### ISSUE TITLE
Survey privacy settings don't work

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform-mobile#117]
Steps:
1. on web, set survey to allow only admins to submit responses 
2. log out of admin on mobile app
3. try to add to that survey on mobile app

Immediately after changing the setting for the survey on web, I logged out of mobile app completely and was still able to see and submit to the survey. Might be lag time again?

The same happens if I set the survey to allow only a custom role as well.

**Comment by dalezak** [comment]
https://github.com/ushahidi/platform-client/blob/8f8ad88a3a92eb107f4da32de03d1104354a7ace/app/main/posts/common/post-survey.service.js#L23
