### ISSUE TITLE
Archived status doesn't appear to work in iOS

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform-mobile#119]
Archived post still appears as published on app after archiving via web (see: https://mobileappqa.ushahidi.io/posts/1), and does not appear under "archived" filter.  After ~20 minutes, the post just doesn't show up anywhere in the mobile app.

**Comment by dalezak** [comment]
Hi @jshorland, I _think_ this is related to the cached data in the app, and need to Pull Down To Refresh the reports in the app.

I made some changes in #116, so perhaps this may not be an issue once that fixes has been rolled out?
