### ISSUE TITLE
Add email under settings doesn't appear to do anything

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform-mobile#120]
Might be a bug in platform? What *should* this result in?

**Comment by dalezak** [comment]
@jshorland I believe this is related to the _Contact email address_ from the backend

![contact_email](https://cloud.githubusercontent.com/assets/91811/25140797/a98d0b2e-241e-11e7-93b8-6f4b8ba86c2a.png)
 
@brandonrosage maybe needs a different label and perhaps a description?

**Comment by dalezak** [comment]
@jshorland @brandonrosage Is this better?

![simulator screen shot apr 18 2017 10 33 29 am](https://cloud.githubusercontent.com/assets/91811/25141949/7d326250-2422-11e7-915c-3441dae9010e.png)
