### ISSUE TITLE
Add Multilingual Support

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform-mobile#123]
https://www.npmjs.com/package/ng2-translate
https://www.npmjs.com/package/google-translate-api

**Comment by tuxpiper** [comment]
Bonus question: how will the community be able to contribute translations? Will we use transifex just like we do in platform-client?

**Comment by dalezak** [comment]
![simulator screen shot jun 28 2017 6 55 21 pm](https://user-images.githubusercontent.com/91811/27666765-6628d9d8-5c33-11e7-9461-79b3771e4c84.png)

**Comment by dalezak** [comment]
![simulator screen shot jun 28 2017 6 55 41 pm](https://user-images.githubusercontent.com/91811/27666772-724f6fc4-5c33-11e7-80c1-7e182c4ecf4a.png)

**Comment by dalezak** [comment]
![simulator screen shot jun 28 2017 6 55 41 pm](https://user-images.githubusercontent.com/91811/27666779-787c6924-5c33-11e7-8e3a-5cec56fa858c.png)

**Comment by dalezak** [comment]
@tuxpiper at the moment I'm using a script which runs the English phrases through Google Translate so the app has 100% translation. The downside is that some of those phrases might not be perfect.

I can explore exporting the phrases to Transifex, and then re-importing them afterwards although not sure whether to include the app phrases in web project? Or if the app should have its own project on Transifex? 

I want to avoid the app having to include un-necessary translations since it will add to the overall size of the app, plus likely slow things down if those translation files are large.

**Comment by tuxpiper** [comment]
yup, I agree that we should have the translations in transifex.

An alternative approach to creating a new transifex project solely for the mobile app may be using the "Resources" feature.

Currently we have just one resource, but I think we could add more. I believe in this way we could partition the translations across resources based on functional areas. From projects we could choose to pull only the resources that are relevant to that specific project.
