### ISSUE TITLE
Title and description are appearing twice in my post after submitting

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform-mobile#130]
But only on the mobile app. It appears normal on the web (https://mobileappqa.ushahidi.io/posts/10)

But the same post viewed on mobile has title and description twice and fields in a different order than the web. 

Testing on iOS with most recent test build

**Comment by dalezak** [comment]
Hmm, previously `Title` and `Description` were default fields that were required on all Surveys. 

Which displayed the Post title and content, is this no longer the case?

**Comment by dalezak** [comment]
Oh, I think I know what's happening!

So duplicate `Title` and `Description` appear, only after creating a post in the app. The reason being, that `"type": "title"` and `"type": "description"` are special cases included in the Forms Attributes. 

On the Add/Edit form, they show up as regular Attribute inputs, the inputted values are being set in the Post title and content but are also being saved as Value, which I'm guessing on the backend are excluded from Values upon saving.
