### ISSUE TITLE
Test API Category Changes  

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform-mobile#136]
https://github.com/ushahidi/platform/issues/1397#issuecomment-304699412

**Comment by dalezak** [comment]
@jess @rjmackay looks like we'll need a new input type for `tags` in the app.

Web https://www.dropbox.com/s/5kjh87moquqb98x/Screenshot%202017-05-30%2013.27.47.png?dl=0

App https://www.dropbox.com/s/jbts3idwfgj4y69/Screenshot%202017-05-30%2013.34.35.png?dl=0

**Comment by dalezak** [comment]
@jshorland @rjmackay Looks like we'll also need to add `Markdown` input type.

**Comment by rjmackay** [comment]
Yup. There's a markdown type now - though adding thats lower priority.
But the `posts.tags` part of a posts response is now replaced by `tags` attribute type instead. 
We've also added hierarchy to tags: each tag has a parent id, and sometimes a children property too

**Comment by dalezak** [comment]
@jshorland @rjmackay No major issues from what I can spot so far, although I will need to add `tags` and `markdown` input types.

Also for some reason the MapBox tiles aren't loading for that deployment, but that might be a different issue, haven't tracked down the cause yet.

**Comment by dalezak** [comment]
@jshorland @rjmackay Can you two add http://qa.ushahididev.com to the app to see if you can spot any issues?

I'm not that familiar with all the backend changes in this release, so you might be able to find some problems I'm not aware if.

**Comment by rjmackay** [comment]
> MapBox tiles aren't loading for that deployment

I think its configured to use the Humanitarian OSM base layer... is that supported in the mobile app?

**Comment by rjmackay** [comment]
Did the mobile app ever show category selection when creating a post? I'm not seeing it on production or staging.
