### ISSUE TITLE
Markdown in site description isn't formatted

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform-mobile#138]
<img width="246" alt="screenshot 2017-05-31 10 52 10" src="https://cloud.githubusercontent.com/assets/7965/26608345/40421f9a-45ef-11e7-86e1-9a92d8174eca.png">

On mobile I see

```
For internal Ushahidi QA 

**Have you tested something today?**
```

**Comment by dalezak** [comment]
Does the site description allow HTML or Markdown?

**Comment by dalezak** [comment]
![simulator screen shot jun 1 2017 10 41 19 am](https://cloud.githubusercontent.com/assets/91811/26690539/ecf0f744-46b6-11e7-8809-3eab67165424.png)
