### ISSUE TITLE
Show Pending Reports

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform-mobile#14]
@brandonrosage Any thoughts how we will handle pending reports? For example, does not have an internet connection and creates some reports offline.

**Comment by brandonrosage** [comment]
I added a new section to the *[Ionic UX Concept](https://docs.google.com/document/d/1oeVcQyrAayWb-twx_QE40P-zOpylTghp0EUoMvq0qPs/edit#bookmark=id.eitr4zfud7d4
)* today that describes how to handle offline implications.

It demonstrates how deployments' overview screen is affected, as well as the "Manage deployments" drawer, various states of the "Responses" screen, and the "Submit a survey response" screen(s).

Sample screen:
![timeline offline](https://cloud.githubusercontent.com/assets/1136279/22529781/5d269bc6-e89e-11e6-814b-4012ccfabc54.png)

**Comment by dalezak** [comment]
@brandonrosage is _Offline_ the right label on the card? If this report hasn't been posted yet, maybe it should say _Pending_ or _Not Posted Yet_ instead? 

The bottom toolbar saying _Offline_ makes sense, but wondering also saying _Offline_ in the card might not be clear?

**Comment by brandonrosage** [comment]
I think you're right, @dalezak. I've revised the various mockups' postcards to use the label "pending."

Sample:
![r1 timeline offline](https://cloud.githubusercontent.com/assets/1136279/22554390/7522a238-e925-11e6-8ae9-2b39a4232493.png)

**Comment by dalezak** [comment]
This has been implemented... closing issue.
