### ISSUE TITLE
pins not appearing on map on both iOS and Android

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform-mobile#143]
Reported by user from collinepisanetour.ushahidi.io on intercom, and replicated by me on both iOS and Android. 

Responses appear in list, but not on map as map markers.

**Comment by dalezak** [comment]
Hmm, is it happening on all deployments? Or just this one deployment?

**Comment by jshorland** [comment]
Confirmed in mobileappqa.ushahidi.io as well

**Comment by rjmackay** [comment]
We made some changes to the API filtering out unmapped posts, its possible we missed something thats causing this. Take a look at the `posts?has_location=mapped` parameter used in the web UI.
If you exclude that you should still get the right data... but maybe we messed up?

**Comment by dalezak** [comment]
Hey @jshorland @rjmackay, I found the problem, looks like I introduced a bug in latest version related to parsing the values to handle tags. 

I'll fix the problem and share a build for testing this morning, if the issue is resolved, I'll submit an update to the App Store.

**Comment by dalezak** [comment]
![simulator screen shot jun 14 2017 11 04 46 am](https://user-images.githubusercontent.com/91811/27145039-593e5510-50f1-11e7-8b6e-61b5ad680116.png)

**Comment by dalezak** [comment]
![simulator screen shot jun 14 2017 11 05 02 am](https://user-images.githubusercontent.com/91811/27145043-5f6a5eb6-50f1-11e7-8d02-5668c27438d8.png)
