### ISSUE TITLE
BEATONA: sign up doesn't work when using an email address already existing in the system

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform-mobile#148]
When I try to sign up with my jess@ushahidi.com (which is already associated with an account in the deployment), it throws an error, but I don't understand what that error means. 

Would be good to make that more human readable so people understand that the email address already exists.

**Comment by dalezak** [comment]
Ah yes, good catch!

**Comment by dalezak** [comment]
![simulator screen shot jul 18 2017 7 33 01 pm](https://user-images.githubusercontent.com/91811/28346710-f2a656da-6bef-11e7-98c9-e6b64bb915a5.png)
