### ISSUE TITLE
Can't write underscore in login email address

### ISSUE THREAD

**Issue by lcenriquez** [ushahidi/platform-mobile#153]
App doesn't let the user type underscore in the email address field. For example: john_snow@domain.com is not allowed.

**Comment by dalezak** [comment]
Hmm, are you using the iOS or Android app? I was able to enter underscore into the email field.

![simulator screen shot jul 19 2017 12 43 45 pm](https://user-images.githubusercontent.com/91811/28383922-08a23dce-6c80-11e7-8433-741695fa7914.png)

@lcenriquez can you login with an underscore in your email into the web deployment?

**Comment by lcenriquez** [comment]
Hi,

Sorry, I believe it was a problem with my iPhone, as I tried again today and it worked. 

Thank you for the fast response and if I find something else I'll let you know ;)

**Comment by dalezak** [comment]
Thanks for checking... closing issue.
