### ISSUE TITLE
BEATONA: Hide Tasks Unless Admin

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform-mobile#158]
https://github.com/ushahidi/platform/issues/1848#issuecomment-316877067

**Comment by dalezak** [comment]
@rjmackay @jshorland just to verify, we should hide Tasks in the mobile app, unless the user is an admin? Is this correct?

**Comment by dalezak** [comment]
@jshorland @rjmackay Are there any other custom roles, besides `admin` that should see Tasks?

**Comment by rjmackay** [comment]
You should check for the users 'Manage Roles' permission
