### ISSUE TITLE
iOS action sheet text should be sentence-case

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform-mobile#2]
Ionic docs show action sheets' text content in sentence-case, which is what we want:

![Ionic](https://cloud.githubusercontent.com/assets/1136279/21197369/d155b352-c200-11e6-810e-6a7c43fcaab6.png)

But the Ushahidi app is all uppercase:

![Ushahidi](https://cloud.githubusercontent.com/assets/1136279/21197395/eb5cff30-c200-11e6-9cd7-235671b8d24a.png)

Let's get it sentence-case.

**Comment by dalezak** [comment]
Oh yes, this is a bug! I applied UPPERCASE styling to `<button>` but unfortunately the side effect was to also UPPERCASE items in Action Sheet menu, I'll remove that and apply `test-uppercase` directive instead for buttons.

**Comment by dalezak** [comment]
Fixed!
![actionsheet](https://cloud.githubusercontent.com/assets/91811/21207614/b140d14a-c22e-11e6-8d60-203d690ef5d9.png)
