### ISSUE TITLE
Test Platform iOS 1.13.0

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform-mobile#23]
### App Launch		
- [ ] Shows splash screen on every app launch																							
- [ ] Shows welcome Let's add your first deployment when there are no deployments
- [ ] Shows the first deployment after a deployment has been added

### Terms of Service		
- [ ] Shows Terms of Service only on first launch
- [ ] Clicking Terms and Conditions opens information in browser
- [ ] Clicking Privacy Policy opens information in browser
- [ ] Accept and Continue enabled after checking I agree to the Terms of Service

### Add First Deployment																										
- [ ] Search by subdomain																								
- [ ] Search by deployment title																								
- [ ] Search by a keyword			
- [ ] Search by deployment URL																					
- [ ] Searches as you type 	
- [ ] Cancel adding a deployment

### Add Second Deployment																									
- [ ] Search by subdomain																								
- [ ] Search by deployment title																								
- [ ] Search by a keyword		
- [ ] Search by deployment URL																						
- [ ] Searches as you type 									

### Delete Deployments																										
- [ ] Delete one of many deployments from side menu																							
- [ ] Delete all the deployments from side menu
- [ ] Shows Add Your First Deployment when last deployment removed

### Change Deployment
- [ ] Change current deployment from side menu

### Change Language
- [ ] Change to another language from side menu
- [ ] Switch back to English from side menu

### Deployment Details
- [ ] Pull down to refresh deployment details
- [ ] View deployment title
- [ ] View deployment description
- [ ] View deployment logo
- [ ] Long description is truncated with Read More
- [ ] Login/Signup visible when logged out
- [ ] Login/Signup NOT visible when logged in
- [ ] Settings visible when logged in as admin
- [ ] Settings NOT visible when logged out or not admin
- [ ] Can click the Submit Survey Response button
- [ ] Share deployment via email
- [ ] Share deployment via message																									

### Deployment Login/Logout																										
- [ ] Login with invalid credentials
- [ ] Login with valid credentials 																					
- [ ] Logout logs out the current user
- [ ] Login/Signup visible after Logout

### Deployment Signup								
- [ ] Signup as new user																					

### Responses List
- [ ] Scroll through list of responses
- [ ] Pull down to refresh should load recent responses
- [ ] Load More button loads more responses
- [ ] Correct survey color displayed on the response card
- [ ] Select a response card to view the response details
- [ ] Edit button visible in response card when have permission
- [ ] Option Share always visible
- [ ] Option Add to Collection visible when logged in
- [ ] Option Archive visible when you have permission
- [ ] Option Publish visible when you have permission
- [ ] Option Delete visible when you have permission

### Responses Map
- [ ] Switch between list view to map mode
- [ ] Pan and zoom the map
- [ ] Change map style to Streets
- [ ] Change map style to Outdoors
- [ ] Change map style to Light
- [ ] Change map style to Dark
- [ ] Change map style to Satellite
- [ ] Change map style to Satellite Streets
- [ ] Click a map pin to see response summary
- [ ] Select the map popup to view the full response details

### Response Filtering																									
- [ ] Filter responses by survey																								
- [ ] Filter responses by status
- [ ] Filter responses by search term		

### Response Details
- [ ] Pull down to refresh response details
- [ ] Scroll through the response details
- [ ] Share response details via email
- [ ] Share response details via message		
- [ ] Edit button visible when you have permission
- [ ] Clicking photo image shows the image view
- [ ] Clicking location image shows the map view
- [ ] Option Share always visible
- [ ] Option Add to Collection visible when logged in
- [ ] Option Archive visible when you have permission
- [ ] Option Publish visible when you have permission
- [ ] Option Delete visible when you have permission

### Deployment Settings																																														
- [ ] Change deployment name																								
- [ ] Change deployment description																									
- [ ] Change deployment contact email

### Add Response
- [ ] Cancel exits adding the response
- [ ] Clicking Create button shows New Response form when only one survey
- [ ] Clicking Create button shows Survey selection sheet when multiple surveys

### Edit Response
- [ ] Cancel exits editing the response
- [ ] Submit changes to response when online
- [ ] Save changes to response locally when offline

### Required Fields
- [ ] Required fields show a red asterix
- [ ] Warning alert displayed when missing required field
- [ ] Required field shows red warning message below

### Field Validation																									
- [ ] Submitting with no required fields in survey																								
- [ ] Submitting with blank required fields																								
- [ ] Submitting with all required fields complete																								
- [ ] Submitting with text in number field																								
- [ ] Submitting with long text in short text field

### Text Input
- [ ] Field focus shows text keyboard

### Number Input
- [ ] Field focus shows number keyboard

### Decimal Input
- [ ] Field focus shows number keyboard

### Markdown Input
- [ ] Field focus shows text keyboard

### Change Date
- [ ] Input date

### Change Date & Time
- [ ] Input date and time

### Select Radio Option
- [ ] Select one of the radio options

### Select Checkbox
- [ ] Select / unselect the checkbox values

### Add Related Post
- [ ] Specify a related post

### Add Photo
- [ ] Add Photo button shows Take Photo option when camera is available
- [ ] Add Photo button shows Photo Library option when library is available
- [ ] Take Photo / Photo Library shows preview of photo
- [ ] Remove Photo removes from your response

### Change Location
- [ ] Change Location button allows drag to new location

### Offline Mode
- [ ] View responses when offline
- [ ] View response details when offline
- [ ] Submit response when offline

**Comment by dalezak** [comment]
@rowasc @Eve-wanderi here's the issue to test Platform iOS 1.13.0, shared via TestFlight.

Includes fixes for https://github.com/ushahidi/account-management/issues/65 and https://github.com/ushahidi/platform-sivico/issues/52.

**Comment by Celestine22** [comment]
@dalezak please share this build with me as well so I can test for iOS
