### ISSUE TITLE
Toggling deployments via drawer ends session

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform-mobile#24]
If I add two deployments using the iOS Simulator, and then I toggle between them via the drawer, the app ends my session (it logs me out) in the deployment I'm leaving. So every time I navigate to a deployment, I have to log in again.

I'm not sure if this is just an issue with sessions on my local install or what. But it's tedious.

**Comment by brandonrosage** [comment]
Nevermind. It's not happening anymore.

**Comment by dalezak** [comment]
I did find a bug with storing the deployment id and the access_token, it should be fixed now if you pull the latest.
