### ISSUE TITLE
Survey fields have unnecessary horizontal lines

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform-mobile#28]
In the compiled app, each field in the survey has two horizontal lines:

![app](https://cloud.githubusercontent.com/assets/1136279/21243458/946ff676-c2de-11e6-89ed-2e3013648a74.png)

The intended design is for only one, which borders the bottom of the input:

![mockup](https://cloud.githubusercontent.com/assets/1136279/21243496/bd6af580-c2de-11e6-9d46-18edbac6d2f0.png)

**Comment by dalezak** [comment]
Baby steps forward...

![survey_1](https://cloud.githubusercontent.com/assets/91811/21251247/f0c918fc-c311-11e6-8585-5ba6b95b6d4b.png)

![survey_2](https://cloud.githubusercontent.com/assets/91811/21251249/f39b5266-c311-11e6-9255-c667917f1fac.png)

![survey_3](https://cloud.githubusercontent.com/assets/91811/21251250/f5fed21c-c311-11e6-94bc-64256f386859.png)

**Comment by dalezak** [comment]
@brandonrosage made some progress on the survey form, but noticed a couple of things.

I'm currently using [Placeholder Labels](http://ionicframework.com/docs/v2/components/#placeholder-labels) for inputs, although realized that once the user has entered information, they won't be able to see what they entered it for. This could be an issue for forms that have multiple text fields, asking different questions.

We might want to explore using either [Stacked Labels](http://ionicframework.com/docs/v2/components/#stacked-labels) and perhaps [Floating Labels](http://ionicframework.com/docs/v2/components/#floating-labels)?

**Comment by brandonrosage** [comment]
Floating labels, please.

**Comment by dalezak** [comment]
Good news, I was able to remove the extra horizontal lines. It is a bit tricky with Ionic to get it exactly like the mockups, but tried to get it as close as possible, we can always revisit and tweak it later.

![form_1](https://cloud.githubusercontent.com/assets/91811/21366042/be720968-c6bd-11e6-9db5-cb6f8d5c20b4.png)

![form_2](https://cloud.githubusercontent.com/assets/91811/21366049/c1b69134-c6bd-11e6-9101-65b37de4a85a.png)

![form_3](https://cloud.githubusercontent.com/assets/91811/21366056/c435c7f4-c6bd-11e6-948f-7901f4e80c5a.png)

![form_4](https://cloud.githubusercontent.com/assets/91811/21366057/c79d9d7c-c6bd-11e6-94f2-fe3bdd2c9f35.png)

![form_5](https://cloud.githubusercontent.com/assets/91811/21366059/ca74b0da-c6bd-11e6-8901-3947812a11b6.png)

**Comment by dalezak** [comment]
Added initial field for each of the attribute types... closing issue.
