### ISSUE TITLE
Location field's default value should be user's current location

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform-mobile#29]
Ideally, any location fields would default their value to the user's current location. And if they select it to change the value, the ideal result would be to transition to a full-screen map screen with a search control at the top to either drag a pin or find a place by keyword search.

Let me know if you need a mockup.

Secondarily, the app's current "detect location" button doesn't do anything when I select it.

**Comment by dalezak** [comment]
![user_location](https://cloud.githubusercontent.com/assets/91811/21269887/1f7b1fa2-c37a-11e6-948b-775ef345411f.png)

**Comment by dalezak** [comment]
D'oh!

Running into this issue showing a Google Map inside of a Modal https://github.com/driftyco/ionic/issues/8761

**Comment by dalezak** [comment]
The Post Form shows the user's current location, but think I'll tackle allowing them to change that location in another issue... closing issue.
