### ISSUE TITLE
'Overview' screen's toolbar is disconnected

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform-mobile#3]
I understand that the mockup for [the deployment overview screen](https://drive.google.com/a/ushahidi.com/file/d/0B76oN-t_b0xBNlFsTWY2c082RjA/view?usp=sharing) suggests a pattern that Ionic doesn't outright support out of the box.

_Intended design:_

![overview](https://cloud.githubusercontent.com/assets/1136279/21197611/ab54d7e0-c201-11e6-9d80-a1b4d528c408.png)

_Current implementation:_

![app](https://cloud.githubusercontent.com/assets/1136279/21197668/e5e1b1b2-c201-11e6-8e64-0a8809d065ff.png)

So I want to figure out how we can reconcile this with custom CSS or a revised design. I do want a splashier treatment for the deployment's name on the over screen.

**Comment by dalezak** [comment]
Does the deployment _Coffeeshops in Austin_ have an image or description?

**Comment by dalezak** [comment]
I pushed a few changes, here's what it currently looks like for https://dale.ushahidi.io.

![deploymentdetails](https://cloud.githubusercontent.com/assets/91811/21208336/154d88a0-c233-11e6-9707-943235a7a41d.png)

**Comment by dalezak** [comment]
Current deployment screen

![deployment_screen](https://cloud.githubusercontent.com/assets/91811/21245728/e8431412-c2e9-11e6-89fd-d7f1390ecd75.png)

**Comment by brandonrosage** [comment]
Unless we can write custom CSS to properly match the mockup and adopt [Material Design's "app bar" with increased height](https://storage.googleapis.com/material-design/publish/material_v_10/assets/0B6Okdz75tqQsSDBhX3BwSURRc1U/layout_structure_appbar_metrics3.png), I think we need to fallback to [Ionic's basic "Navbar."](http://ionicframework.com/docs/v2/api/components/navbar/Navbar/)

Desired layout:

![material design mock](https://cloud.githubusercontent.com/assets/1136279/21655526/04a1c2d4-d280-11e6-86a1-e19b3c8ff905.png)

**Comment by dalezak** [comment]
@brandonrosage Hmm, I'm not sure how best to implement this design. 

We could have a second [NavBar](http://ionicframework.com/docs/v2/api/components/navbar/Navbar/) or [Toolbar](http://ionicframework.com/docs/v2/api/components/toolbar/Toolbar/) below the main NavBar, however neither have left aligned text or wrapping text like in the mockups.

This is how the [NavBar](http://ionicframework.com/docs/v2/api/components/navbar/Navbar/) and [Toolbar](http://ionicframework.com/docs/v2/api/components/toolbar/Toolbar/) look on iOS.

![navbar_ios](https://cloud.githubusercontent.com/assets/91811/22655022/5787d0a4-ec54-11e6-92a4-022e0832163e.png)

And on Android in Ionic.

![navbar_android](https://cloud.githubusercontent.com/assets/91811/22655029/5c64c320-ec54-11e6-9c1f-08a0f2faa3dc.png)

**Comment by brandonrosage** [comment]
Alright. If it's not possible to customize the structure of the toolbar/navbar right now, let's do something more simple:

![d1 overview](https://cloud.githubusercontent.com/assets/1136279/22659003/b141d2fe-ec61-11e6-8687-cd188617607b.png)

I've updated [the Ionic UX Concept](https://docs.google.com/document/d/1oeVcQyrAayWb-twx_QE40P-zOpylTghp0EUoMvq0qPs/edit?usp=sharing) and supporting mockups to reflect this revision, which essentially leaves the D1 toolbar without a title (just a menu and share trigger). And the deployment's name becomes display text in the body of the screen.

**Comment by dalezak** [comment]
Cool, I like that, seems pretty clean as well (y)

**Comment by dalezak** [comment]
Updating the deployment title... closing issue.
