### ISSUE TITLE
Survey form's 'submit' button should be in toolbar

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform-mobile#30]
The compiled app currently has a "Post response" button at the bottom of the content area:

![app](https://cloud.githubusercontent.com/assets/1136279/21243807/265d1158-c2e0-11e6-980b-d5cb4ec90ad9.png)

The 'submit' button was intended to be in the toolbar, using Ionic's "send" icon:

![mock](https://cloud.githubusercontent.com/assets/1136279/21243816/323aac24-c2e0-11e6-80c5-b46e54d231e6.png)

**Comment by dalezak** [comment]
![submitresponse](https://cloud.githubusercontent.com/assets/91811/21245698/c50d40d0-c2e9-11e6-92e6-03ae8f160f81.png)
