### ISSUE TITLE
Survey form should include colored 'band' along left edge

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform-mobile#31]
Much like the cards that hold response summaries in the TImeline, survey forms and response detail screens should include the appropriate survey's color "band" along its left edge.

Survey:

![survey](https://cloud.githubusercontent.com/assets/1136279/21243856/777cd794-c2e0-11e6-8dae-ca57d627befb.png)

Response detail:

![response detail](https://cloud.githubusercontent.com/assets/1136279/21243871/88378778-c2e0-11e6-8850-082965e1940e.png)

**Comment by dalezak** [comment]
![formcolor](https://cloud.githubusercontent.com/assets/91811/21246040/cda7a954-c2eb-11e6-9f5d-c5ea09e5cde2.png)

**Comment by dalezak** [comment]
Done and done!
