### ISSUE TITLE
Required fields need more subtle, conditional treatment

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform-mobile#43]
The current build treats required fields with both the asterisk and the message "Text required," in red:

![survey](https://cloud.githubusercontent.com/assets/1136279/21655811/22fdcd94-d281-11e6-9d55-99e7f67c8b0a.png)

The intended treatment is for required fields to adopt the following treatment by default:

![required, default](https://cloud.githubusercontent.com/assets/1136279/21655884/6374b4a0-d281-11e6-84e1-3729532be9ed.png)

Note that they don't necessarily need any text description re-emphasizing that it's required.

If the user brings that field into focus, the floating label takes on color (including a red asterisk):

![required, focus](https://cloud.githubusercontent.com/assets/1136279/21655933/94a093be-d281-11e6-9012-78c68c22e37a.png)
 
And only if the user tries to submit the survey without completing a required field do they get the red-colored input line and error message below the field:

![required, error](https://cloud.githubusercontent.com/assets/1136279/21656018/ed19dc08-d281-11e6-9b9e-08038090676e.png)

**Comment by dalezak** [comment]
Error message initially hidden for required fields until user submits the form... closing issue.
