### ISSUE TITLE
Response detail views should display their survey name in the toolbar

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform-mobile#44]
When looking at a response's detail view, the current build displays the contents of the response's "title" field in the toolbar:

![response title](https://cloud.githubusercontent.com/assets/1136279/21656524/1b48c600-d284-11e6-9db2-1fd46e7ac98f.png)

The intention is, instead, for [the response's survey name to occupy that space in the toolbar](https://drive.google.com/a/ushahidi.com/file/d/0B76oN-t_b0xBMkVWOVJTeThUbkU/view?usp=sharing). This is due, in part, to the fact that surveys will soon *not* assume a title field. They can have any combination and order of fields and field types.

**Comment by dalezak** [comment]
This issue has been fixed.... closing issue.
