### ISSUE TITLE
FAB should be fixed/sticky

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform-mobile#45]
I don't know if Ionic is to blame or not, but the FAB button is strangely not sticky in the current build:

![FAB bug](https://cloud.githubusercontent.com/assets/1136279/21656729/ea8fd7a0-d284-11e6-8d65-b3762ff5c1ee.png)

Obviously, it should always remain in the bottom-right, no matter the scroll position.

**Comment by dalezak** [comment]
Oh, looks like this was related to switching between list and map, the issue has been fixed... closing issue.
