### ISSUE TITLE
Add Background To Welcome Screen

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform-mobile#5]
![o1 1](https://cloud.githubusercontent.com/assets/91811/21242313/54d90f52-c2d9-11e6-9223-939b31c95799.png)

**Comment by dalezak** [comment]
@brandonrosage Can you share the background image for this screen?

**Comment by brandonrosage** [comment]
Here's the image: https://www.dropbox.com/s/a7uwnb1f5jupd5o/splash-bg.png?dl=0

**Comment by dalezak** [comment]
![welcomescreen](https://cloud.githubusercontent.com/assets/91811/21245473/35cead4c-c2e8-11e6-97ac-eb7f01acf66d.png)
