### ISSUE TITLE
Testing the app  using our server.

### ISSUE THREAD

**Issue by frasanz** [ushahidi/platform-mobile#55]
Hello.

We've created our own platform (web-client + api) inside:

http://ushahidi.ibercivis.es/platform/api/v3/config
http://ushahidi.ibercivis.es/

I've compiled the android app. As you know, the first screen is the deployments one, but I want to point (allways) to our server (only one deployment)

I think I don't understand very well the topology. Can I create a platform  and the create deployments (like ushahidi one?

**Comment by dalezak** [comment]
Hi frasanz, the app is still under development, and currently hardcoded to ushahidi.io domain. I'll explore the option to specify a custom domain for it to sync with.

**Comment by frasanz** [comment]
Thanks, I'll appreciate it very much,

Regards,
Fran

2017-02-01 21:51 GMT+01:00 Dale Zak <notifications@github.com>:

**Comment by dalezak** [comment]
Created https://github.com/ushahidi/platform/issues/1638 related to the Platform returning the location of the API for custom deployments.

**Comment by dalezak** [comment]
Hey @frasanz, good news!

This functionality has now been implemented in https://github.com/ushahidi/platform-mobile/issues/103, thanks to @willdoran backend changes for https://github.com/ushahidi/platform/issues/1638.

The app now checks for `config.json` file on a deployment to determine the API location, so you'll need to pull and merge those changes into your deployment to make it work.

This fix will be included in upcoming 1.2 update of the iOS and Android, hopefully will be submitted for review later this week.
