### ISSUE TITLE
Deployment 'overview' screen should make responses accessible to logged out users

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform-mobile#63]
When navigating a deployment for which I'm not logged in, I should be able to:

* View Published responses.
* Submit survey responses to surveys that allow anonymous submissions.

[The UX Concept now addresses this scenario](https://docs.google.com/document/d/1oeVcQyrAayWb-twx_QE40P-zOpylTghp0EUoMvq0qPs/edit#heading=h.tghy26fda1xl).

_Example 'overview' screen when logged out_

![Overview, logged out](https://cloud.githubusercontent.com/assets/1136279/23312410/47228d38-fa7f-11e6-9417-24e73ecbf941.png)

**Comment by dalezak** [comment]
Alright, you can now access deployment responses before you login, with limited permissions. Once you login, you then have the associated permissions for that user... closing issue.
