### ISSUE TITLE
FAB button is too small

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform-mobile#64]
I don't know if Ionic spits them out that small, but the tap target is far too small. It should be 56px x 56px.

Current size:

![image](https://cloud.githubusercontent.com/assets/1136279/23313021/885b8172-fa81-11e6-92cc-7e41181c58df.png)

**Comment by dalezak** [comment]
Ok, looks like I was using `mini` attribute, I've removed it so now is the default size... closing issue.
