### ISSUE TITLE
Deployment 'settings' screen should include actions in app bar

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform-mobile#65]
The target to save any changes to deployment settings should be in the app bar (e.g. "Done") and not the body of the screen:

![image](https://cloud.githubusercontent.com/assets/1136279/23313214/67390306-fa82-11e6-8a85-fb342ef6b0dc.png)

It's currently a primary button in the body content:

![image](https://cloud.githubusercontent.com/assets/1136279/23313287/bb76f130-fa82-11e6-8afd-ecdfc74ff0f9.png)

**Comment by dalezak** [comment]
Alright, I made Settings a modal popup, with X and Done buttons... closing issue.
