### ISSUE TITLE
Bug: Surveys disappear after applying a filter

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform-mobile#67]
I'm experiencing the following bug 100 percent of the time: If I apply any combination of filters, surveys go completely missing from the deployment. By that I mean, they no longer appear in the filters fieldset of surveys...

![filters](https://cloud.githubusercontent.com/assets/1136279/23316887/e2684ece-fa91-11e6-94d6-46fd210111e3.png)

...and they go missing from the action sheet for submitting a survey response:

![action sheet](https://cloud.githubusercontent.com/assets/1136279/23316906/fb988224-fa91-11e6-9990-d6cd13d36d81.png)

Even after I clear the filters, this problem persists. I have to remove the deployment from the app all together and re-add it in order to see the surveys, again.

**Comment by dalezak** [comment]
Hmm, this is weird! I'm not experiencing this issue, does the deployment you're testing have a survey?

**Comment by brandonrosage** [comment]
Yes, it does. They disappear only after applying a filter.

**Comment by brandonrosage** [comment]
With the latest update, this problem is resolved.
