### ISSUE TITLE
Implement Logout Of Deployment

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform-mobile#7]

**Comment by dalezak** [comment]
@brandonrosage Where does _Logout_ happen? Will there be a button / row at the bottom of the _Deployment Details_ screen?

**Comment by brandonrosage** [comment]
The intended path is (via [the deployment's overview screen](https://drive.google.com/a/ushahidi.com/file/d/0B76oN-t_b0xBNlFsTWY2c082RjA/view?usp=sharing)) Settings: User name > Your account...

![Your account](https://cloud.githubusercontent.com/assets/1136279/21242900/3055e300-c2dc-11e6-965b-98344b6fb424.png)

**Comment by dalezak** [comment]
Initial logout functionality has been added... closing issue.
