### ISSUE TITLE
Remove "+" button in the toolbar for the menu

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform-mobile#76]
Let's get rid of the "+" icon button in the toolbar atop the "Deployments" menu. It's a redundancy that's doing more harm than good, I think. 

Leave the "+ Add deployment" button as it is, of course.

![MENU](https://cloud.githubusercontent.com/assets/1136279/23520802/0a568716-ff42-11e6-8b65-c6676129c294.png)

**Comment by dalezak** [comment]
Good call 👍

**Comment by dalezak** [comment]
Plus from menu removed... closing issue.
