### ISSUE TITLE
Manage Deployments

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform-mobile#8]
![d2- manage deployments](https://cloud.githubusercontent.com/assets/91811/21242521/5600ba64-c2da-11e6-8209-10060859b436.png)

**Comment by jshorland** [comment]
lookin’ good gents.

**Comment by dalezak** [comment]
@brandonrosage Do you think we need a separate screen for this? Or could it be handled from the side menu using slide functionality? http://ionicframework.com/docs/v2/components/#sliding-list

![delete-example](https://cloud.githubusercontent.com/assets/91811/21242573/a2b99d62-c2da-11e6-8c98-ad03ad15a454.gif)

**Comment by brandonrosage** [comment]
I think that's a great idea, Dale. Let's do that.

I think the drawer will need to have the "Add deployment" call to action in the list, however. Not just the "+" in the toolbar.

**Comment by dalezak** [comment]
![managedeployments](https://cloud.githubusercontent.com/assets/91811/21244864/23c1d992-c2e5-11e6-8d36-f3cfe1b69197.png)

**Comment by brandonrosage** [comment]
Baller!
