### ISSUE TITLE
Map view should fit its bounds to markers

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform-mobile#85]
Currently, when I switch to "map" view on a deployment's responses, it centers and zooms to Austin, TX -- my location. I'd expect it to center and zoom (fit its bounds) to the markers for the responses.

One of the biggest problems with this bug is that, for most deployments, switching to map view displays no markers. Just a plain map of my region. It's confusing if you don't understand what's going on.

**Comment by dalezak** [comment]
The map is now centered at the latitude and longitude provided the API

**Comment by dalezak** [comment]
This should be good enough for now... closing issue.
