### ISSUE TITLE
Adding some deployments throws an error related to authentication

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/platform-mobile#90]
Specifically trying to add "kentucky.ushahidi.io"

![image uploaded from ios 1](https://cloud.githubusercontent.com/assets/106068/24164672/d90aab26-0e44-11e7-9285-f100cf5386e9.jpg)

**Comment by dalezak** [comment]
Looks like that deployment is only `reserved` https://api.ushahidi.io/deployments?q=kentucky, I'll need to exclude those from the search results.

**Comment by dalezak** [comment]
Thanks for reporting this @brianherbert, I pushed a fix to only show deployments that are `deployed`, the fix will be included in 1.2... closing issue.
