### ISSUE TITLE
Adding safecity deployment gives "problem logging in" 405

### ISSUE THREAD

**Issue by mackers** [ushahidi/platform-mobile#92]
1.0 for Android

1. Add deployment "safecity.ushahidi.io"
2. Get following error:

![photo on 22-03-2017 at 10 54](https://cloud.githubusercontent.com/assets/233644/24194437/0696562c-0eee-11e7-94ee-c50862984686.jpg)

**Comment by dalezak** [comment]
Thanks @mackers, Brian also found this issue yesterday https://github.com/ushahidi/platform-mobile/issues/90, I'm including a fix in 1.2.

Looks like the deployment search was including results for deployments that were only `reserved` and not `deployed` yet, I'm excluding those now.
